services:
  db:
    image: postgres:16.2
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - backend


volumes:
  postgres_data:

networks:
  backend:
    driver: bridge

